function atree = t2pmodel(t)
%T2MODEL learns a probabilistic model for the given tree structure.
% 
% inputs:
%   t     tree structure as generated by HC.
%
% outputs:
%   atree probabilistic model based on latent trees
%
% note that if latent nodes have only a single state, they become
% roots.  thus the resulting tree might have more roots than the
% initial one.
%
% Stefan Harmeling * 18-FEB-2010

