function str = data2zhang(d)
% generates a text file with the data which corresponds to the format Zhang
% is expecting for his Java code.
%
% Copyright (C) 2006 - 2009 by Stefan Harmeling (2009-06-26).

f = sample2freq(d);  % get frequencies
nsyms = d.nsyms;

str = '//Data table generated by ''data2zhang.m''';

str = sprintf('%s\n\nName: %s\n\n', str, d.name);
str = sprintf('%s//Variables:\n', str);
for i = 1:length(nsyms)
  str = sprintf('%svar%03d:', str, i);
  for j = 1:nsyms(i)
    str = sprintf('%s s%02d ', str, j-1);
  end
  str = sprintf('%s\n', str);
end
str = sprintf('%s\n//Records:\n', str);
for i = 1:size(f, 1)
  str = [str sprintf('%d ', f(i,1:end-1)-1)];
  str = [str sprintf('%.1f\n', f(i,end))];
end
str = [str sprintf('//Total count: %.1f\n', sum(f(:,end)))];

